using System;
using System.Collections.Generic;
using System.IO;
using CommandLine;
using Newtonsoft.Json;

namespace Passive.Discord.Setup
{
    public class Config
    {
        private static string savePath = Path.Combine(AppContext.BaseDirectory, "Config.json");

        public enum Defaults
        {
            Token,

            Prefix,

            ShardCount
        }

        public Dictionary<string, string> Entries { get; set; } = new Dictionary<string, string>();

        public static Config LoadFromFile(string path)
        {
            Config config;
            if (path == null)
            {
                path = savePath;
            }

            if (File.Exists(path))
            {
                var file = File.ReadAllText(path);
                config = JsonConvert.DeserializeObject<Config>(file);
                savePath = path;
            }
            else
            {
                config = GenerateAndSaveDefaultConfig(path);
            }

            return config;
        }

        public static Config ParseArguments(string[] args = null)
        {
            Config config = null;
            if (args != null)
            {
                Parser.Default.ParseArguments<Options>(args)
                    .WithParsed(o =>
                    {
                        config = LoadFromFile(o.ConfigPath);
                    });
            }

            config ??= LoadFromFile(null);
            return config;
        }

        /// <summary>
        /// Gets the specified entry or adds it and saves the config, returning the newly generated value.
        /// </summary>
        /// <param name="key">The identification key used to locate the value.</param>
        /// <param name="generationMethod">A function used in order to generate a new value for the given key.</param>
        /// <returns>The specified entry for the given key.</returns>
        public string GetOrAddEntry(string key, Func<string> generationMethod)
        {
            if (!Entries.ContainsKey(key))
            {
                Entries.Add(key, generationMethod());
                Save();
            }

            return Entries[key];
        }

        /// <summary>
        /// Saves the config to the last save path (generated by the LoadFromFile method).
        /// </summary>
        public void Save()
        {
            File.WriteAllText(savePath, JsonConvert.SerializeObject(this, Formatting.Indented));
        }

        private static Config GenerateAndSaveDefaultConfig(string path)
        {
            savePath = path;
            var config = new Config();
            File.WriteAllText(path, JsonConvert.SerializeObject(config));
            return config;
        }
    }
}